---

- name: Fail for missing "remote_user"
  fail: msg="This role requires remote_user to be set and non empty. Please refer to the README."
  when: remote_user is not defined or remote_user == '')

- name: (00) Install Java and basic RPM dependencies
  become: true
  yum: name={{ item }} state=present
  with_items:
   - unzip
   - "{{ java_pkg_name }}"
   - rsync
   # for netstat
   - net-tools
   # for pstree
   - psmisc
   # for vimdiff
   - vim

# Set in the DEV environment during the first setup
- name: (00) {dev} Copy .bashrc
  template:
    src: .bashrc.j2
    dest: "/home/{{ remote_user }}/.bashrc"
    owner: "{{ remote_user }}"
  register: bashrc_uploaded

# Set in the DEV environment during the first setup
- name: (00) {dev} Set server timezone
  become: true
  when: bashrc_uploaded.changed == True
  command: "timedatectl set-timezone {{ timezone }}"
